name: hamburg_mobility
version: "1.0.0"
config-version: 2
profile: hamburg_mobility
model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]
models:
  hamburg_mobility:
    staging:
      +materialized: view
    marts:
      +materialized: table
